linear_solver   =                "ma97"

sampling_time    =    0.1
time_horizon     =    2.0

number_of_maximum_contacts    =  2
number_of_slices              =  1
static_friction_coefficient   =  0.33

# com_weight                  =   [10.0, 10.0, 200.0]
# contact_position_weight     =   2e2
# force_rate_of_change_weight =   [10.0, 10.0, 10.0]
# angular_momentum_weight     =   20.0
# contact_force_symmetry_weight = 10.0

com_weight                  =   [7.39551000e2,  4.22028000e2, 8.95235000e2]
contact_position_weight     =   2.16436000e2
force_rate_of_change_weight =   [1.68915000e2,  7.01971000e2, 6.31974481e-1]
angular_momentum_weight     =   1.21310000e1
contact_force_symmetry_weight = 1.44145000e2

# ipopt_max_iteration         =   10
solver_verbosity            =   0
is_warm_start_enabled       =   true
ipopt_tolerance             =   1e-5

[CONTACT_0]
number_of_corners = 4
contact_name  = "left_foot"
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
bounding_box_upper_limit  = [0.0, 0.0, 0.0]
bounding_box_lower_limit  = [-0.0, -0.0, 0.0]

[CONTACT_1]
number_of_corners = 4
contact_name  = "right_foot"
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
bounding_box_upper_limit   = [0.0, 0.0, 0.0]
bounding_box_lower_limit   = [-0.0, -0.0, 0.0]
