linear_solver   =                "ma97"

controller_sampling_time    =    0.1
controller_horizon          =    9

number_of_maximum_contacts    =   2
number_of_slices              =    1
static_friction_coefficient   =  0.33

com_weight                  =   [10.0, 10.0, 200.0]
contact_position_weight     =   2e2
force_rate_of_change_weight =   [10.0, 10.0, 10.0]
angular_momentum_weight     =   1.0
ipopt_max_iteration         =   6
solver_verbosity            =   0

[CONTACT_0]
number_of_corners = 4
contact_name  = "left_foot"
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
bounding_box_upper_limit  = [0.01, 0.05, 0.0]
bounding_box_lower_limit  = [-0.01, -0.0, 0.0]

[CONTACT_1]
number_of_corners = 4
contact_name  = "right_foot"
corner_0  = [0.08, 0.03, 0.0]
corner_1  = [0.08, -0.03, 0.0]
corner_2  = [-0.08, -0.03, 0.0]
corner_3  = [-0.08, 0.03, 0.0]
bounding_box_upper_limit   = [0.01, 0.0, 0.0]
bounding_box_lower_limit   = [-0.01, -0.05, 0.0]
